# Just like config/database.yml, this file requires an entry for each environment
# http://aws.amazon.com/security-credentials

development:
  host: localhost
  
test:
  region: eu-west-1

production:
  region: eu-west-1